# Application
server:
  port: 8080
  servlet:
    context-path: /api

# Database
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
jwt:
  secret-key: "KzpX1FuyDVnns8zkFeKXo6lINb0hSM3qVkEeWRuF5UGCy7oI32fcJbRzQpfG5Jkk"
  validation-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds

bcrypt:
  salt-length: 10

# Documentation
springdoc:
  api-docs:
      path: /docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

open:
  api:
    title: Identity Service
    version: 1.0
    description: A service to handle security control like authentication and authentication APIs.
